# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'calv3.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


import sys
import math
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QApplication, QWidget, QPushButton
from PyQt5.QtGui import QIcon
# 设置任务栏图标
import ctypes
ctypes.windll.shell32.SetCurrentProcessExplicitAppUserModelID("myappid")


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setFixedSize(517, 470)
        # 设置窗口图标
        MainWindow.setWindowIcon(QIcon('cal.ico'))

        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.op_c = QtWidgets.QPushButton(self.centralwidget)
        self.op_c.setGeometry(QtCore.QRect(30, 150, 98, 50))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(22)
        font.setBold(False)
        font.setWeight(50)
        self.op_c.setFont(font)
        self.op_c.setStyleSheet("color: rgb(255, 0, 0);")
        self.op_c.setObjectName("op_c")
        self.op_b = QtWidgets.QPushButton(self.centralwidget)
        self.op_b.setGeometry(QtCore.QRect(150, 150, 98, 50))
        font = QtGui.QFont()
        font.setFamily("等线")
        font.setPointSize(22)
        font.setBold(False)
        font.setWeight(75)
        self.op_b.setFont(font)
        self.op_b.setStyleSheet("color: rgb(255, 170, 0);")
        self.op_b.setObjectName("op_b")
        self.op_sqrt = QtWidgets.QPushButton(self.centralwidget)
        self.op_sqrt.setGeometry(QtCore.QRect(270, 150, 98, 50))
        font = QtGui.QFont()
        font.setFamily("等线")
        font.setPointSize(22)
        font.setBold(False)
        font.setWeight(75)
        self.op_sqrt.setFont(font)
        self.op_sqrt.setStyleSheet("color: rgb(255, 170, 0);")
        self.op_sqrt.setObjectName("op_sqrt")
        self.num_7 = QtWidgets.QPushButton(self.centralwidget)
        self.num_7.setGeometry(QtCore.QRect(30, 210, 98, 50))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(22)
        font.setBold(False)
        font.setWeight(50)
        self.num_7.setFont(font)
        self.num_7.setStyleSheet("color: rgb(0, 85, 255);")
        self.num_7.setObjectName("num_7")
        self.num_8 = QtWidgets.QPushButton(self.centralwidget)
        self.num_8.setGeometry(QtCore.QRect(150, 210, 98, 50))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(22)
        font.setBold(False)
        font.setWeight(50)
        self.num_8.setFont(font)
        self.num_8.setStyleSheet("color: rgb(0, 85, 255);")
        self.num_8.setObjectName("num_8")
        self.num_9 = QtWidgets.QPushButton(self.centralwidget)
        self.num_9.setGeometry(QtCore.QRect(270, 210, 98, 50))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(22)
        font.setBold(False)
        font.setWeight(50)
        self.num_9.setFont(font)
        self.num_9.setStyleSheet("color: rgb(0, 85, 255);")
        self.num_9.setObjectName("num_9")
        self.num_4 = QtWidgets.QPushButton(self.centralwidget)
        self.num_4.setGeometry(QtCore.QRect(30, 270, 98, 50))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(22)
        font.setBold(False)
        font.setWeight(50)
        self.num_4.setFont(font)
        self.num_4.setStyleSheet("color: rgb(0, 85, 255);")
        self.num_4.setObjectName("num_4")
        self.num_5 = QtWidgets.QPushButton(self.centralwidget)
        self.num_5.setGeometry(QtCore.QRect(150, 270, 98, 50))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(22)
        font.setBold(False)
        font.setWeight(50)
        self.num_5.setFont(font)
        self.num_5.setStyleSheet("color: rgb(0, 85, 255);")
        self.num_5.setObjectName("num_5")
        self.num_6 = QtWidgets.QPushButton(self.centralwidget)
        self.num_6.setGeometry(QtCore.QRect(270, 270, 98, 50))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(22)
        font.setBold(False)
        font.setWeight(50)
        self.num_6.setFont(font)
        self.num_6.setStyleSheet("color: rgb(0, 85, 255);")
        self.num_6.setObjectName("num_6")
        self.num_1 = QtWidgets.QPushButton(self.centralwidget)
        self.num_1.setGeometry(QtCore.QRect(30, 330, 98, 50))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(22)
        font.setBold(False)
        font.setWeight(50)
        self.num_1.setFont(font)
        self.num_1.setStyleSheet("color: rgb(0, 85, 255);")
        self.num_1.setObjectName("num_1")
        self.num_2 = QtWidgets.QPushButton(self.centralwidget)
        self.num_2.setGeometry(QtCore.QRect(150, 330, 98, 50))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(22)
        font.setBold(False)
        font.setWeight(50)
        self.num_2.setFont(font)
        self.num_2.setStyleSheet("color: rgb(0, 85, 255);")
        self.num_2.setObjectName("num_2")
        self.num_3 = QtWidgets.QPushButton(self.centralwidget)
        self.num_3.setGeometry(QtCore.QRect(270, 330, 98, 50))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(22)
        font.setBold(False)
        font.setWeight(50)
        self.num_3.setFont(font)
        self.num_3.setStyleSheet("color: rgb(0, 85, 255);")
        self.num_3.setObjectName("num_3")
        self.num_0 = QtWidgets.QPushButton(self.centralwidget)
        self.num_0.setGeometry(QtCore.QRect(30, 390, 98, 50))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(22)
        font.setBold(False)
        font.setWeight(50)
        self.num_0.setFont(font)
        self.num_0.setStyleSheet("color: rgb(0, 85, 255);")
        self.num_0.setObjectName("num_0")
        self.num_dot = QtWidgets.QPushButton(self.centralwidget)
        self.num_dot.setGeometry(QtCore.QRect(150, 390, 98, 50))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(22)
        font.setBold(False)
        font.setWeight(50)
        self.num_dot.setFont(font)
        self.num_dot.setStyleSheet("color: rgb(0, 85, 255);")
        self.num_dot.setObjectName("num_dot")
        self.op_devide = QtWidgets.QPushButton(self.centralwidget)
        self.op_devide.setGeometry(QtCore.QRect(390, 150, 98, 50))
        font = QtGui.QFont()
        font.setFamily("等线")
        font.setPointSize(22)
        font.setBold(False)
        font.setWeight(75)
        self.op_devide.setFont(font)
        self.op_devide.setStyleSheet("color: rgb(255, 170, 0);")
        self.op_devide.setObjectName("op_devide")
        self.op_multi = QtWidgets.QPushButton(self.centralwidget)
        self.op_multi.setGeometry(QtCore.QRect(390, 210, 98, 50))
        font = QtGui.QFont()
        font.setFamily("等线")
        font.setPointSize(22)
        font.setBold(False)
        font.setWeight(75)
        self.op_multi.setFont(font)
        self.op_multi.setStyleSheet("color: rgb(255, 170, 0);")
        self.op_multi.setObjectName("op_multi")
        self.op_minus = QtWidgets.QPushButton(self.centralwidget)
        self.op_minus.setGeometry(QtCore.QRect(390, 270, 98, 50))
        font = QtGui.QFont()
        font.setFamily("等线")
        font.setPointSize(22)
        font.setBold(False)
        font.setWeight(75)
        self.op_minus.setFont(font)
        self.op_minus.setStyleSheet("color: rgb(255, 170, 0);")
        self.op_minus.setObjectName("op_minus")
        self.op_plus = QtWidgets.QPushButton(self.centralwidget)
        self.op_plus.setGeometry(QtCore.QRect(390, 330, 98, 50))
        font = QtGui.QFont()
        font.setFamily("等线")
        font.setPointSize(22)
        font.setBold(False)
        font.setWeight(75)
        self.op_plus.setFont(font)
        self.op_plus.setStyleSheet("color: rgb(255, 170, 0);")
        self.op_plus.setObjectName("op_plus")
        self.op_equal = QtWidgets.QPushButton(self.centralwidget)
        self.op_equal.setGeometry(QtCore.QRect(267, 390, 221, 50))
        font = QtGui.QFont()
        font.setFamily("等线")
        font.setPointSize(22)
        font.setBold(False)
        font.setWeight(75)
        self.op_equal.setFont(font)
        self.op_equal.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(255, 170, 0);")
        self.op_equal.setObjectName("op_equal")

        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(30, 20, 461, 111))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(28)
        font.setBold(False)
        font.setWeight(50)
        self.lineEdit.setFont(font)
        self.lineEdit.setStatusTip("")
        self.lineEdit.setWhatsThis("")
        self.lineEdit.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing)
        self.lineEdit.setObjectName("lineEdit")

        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(40, 30, 441, 41))
        font = QtGui.QFont()
        font.setFamily("等线")
        font.setPointSize(18)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")

        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 517, 23))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        # 设置按钮点击事件后执行对应的自定义函数
        self.num_0.clicked.connect(self.ps_num_0)
        self.num_1.clicked.connect(self.ps_num_1)
        self.num_2.clicked.connect(self.ps_num_2)
        self.num_3.clicked.connect(self.ps_num_3)
        self.num_4.clicked.connect(self.ps_num_4)
        self.num_5.clicked.connect(self.ps_num_5)
        self.num_6.clicked.connect(self.ps_num_6)
        self.num_7.clicked.connect(self.ps_num_7)
        self.num_8.clicked.connect(self.ps_num_8)
        self.num_9.clicked.connect(self.ps_num_9)
        self.op_plus.clicked.connect(self.ps_plus)
        self.op_minus.clicked.connect(self.ps_minus)
        self.op_multi.clicked.connect(self.ps_multi)
        self.op_devide.clicked.connect(self.ps_devide)
        self.op_equal.clicked.connect(self.calcu)
        self.op_c.clicked.connect(self.ps_CE)
        self.op_b.clicked.connect(self.ps_back)
        self.op_sqrt.clicked.connect(self.ps_sqrt)
        self.num_dot.clicked.connect(self.ps_dot)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Calculator"))
        self.op_c.setText(_translate("MainWindow", "C"))
        self.op_b.setText(_translate("MainWindow", "<"))
        self.op_sqrt.setText(_translate("MainWindow", "√"))
        self.num_7.setText(_translate("MainWindow", "7"))
        self.num_8.setText(_translate("MainWindow", "8"))
        self.num_9.setText(_translate("MainWindow", "9"))
        self.num_4.setText(_translate("MainWindow", "4"))
        self.num_5.setText(_translate("MainWindow", "5"))
        self.num_6.setText(_translate("MainWindow", "6"))
        self.num_1.setText(_translate("MainWindow", "1"))
        self.num_2.setText(_translate("MainWindow", "2"))
        self.num_3.setText(_translate("MainWindow", "3"))
        self.num_0.setText(_translate("MainWindow", "0"))
        self.num_dot.setText(_translate("MainWindow", "."))
        self.op_devide.setText(_translate("MainWindow", "/"))
        self.op_multi.setText(_translate("MainWindow", "*"))
        self.op_minus.setText(_translate("MainWindow", "-"))
        self.op_plus.setText(_translate("MainWindow", "+"))
        self.op_equal.setText(_translate("MainWindow", "="))

        self.lineEdit.setText(_translate("MainWindow", ""))
        self.label.setText(_translate("MainWindow", ""))

    # 设置按钮点击后执行相应的自定义函数
    def ps_CE(self):
        self.lineEdit.clear()
        self.label.clear()

    def ps_num_1(self):
        self.lineEdit.insert('1')

    def ps_num_0(self):
        self.lineEdit.insert('0')

    def ps_num_2(self):
        self.lineEdit.insert('2')

    def ps_num_3(self):
        self.lineEdit.insert('3')

    def ps_num_4(self):
        self.lineEdit.insert('4')

    def ps_num_5(self):
        self.lineEdit.insert('5')

    def ps_num_6(self):
        self.lineEdit.insert('6')

    def ps_num_7(self):
        self.lineEdit.insert('7')

    def ps_num_8(self):
        self.lineEdit.insert('8')

    def ps_num_9(self):
        self.lineEdit.insert('9')

    def ps_plus(self):
        self.lineEdit.insert('+')

    def ps_minus(self):
        self.lineEdit.insert('-')

    def ps_multi(self):
        self.lineEdit.insert('*')

    def ps_devide(self):
        self.lineEdit.insert('/')

    def ps_back(self):
        t = self.lineEdit.text()
        tt = t[:-1]
        self.lineEdit.setText(tt)

    def ps_dot(self):
        self.lineEdit.insert('.')

    def calcu(self):
        text = self.lineEdit.text()
        try:
            result = eval(text)
            self.label.setText(text)
            self.lineEdit.setText(str(eval(text)))
        except:
            self.lineEdit.setText('输入错误')

    def ps_sqrt(self):
        textq = self.lineEdit.text()
        try:
            self.label.setText('√' + str(textq))
            self.lineEdit.setText(str(math.sqrt(eval(textq))))
        except:
            self.lineEdit.setText('输入错误')


if __name__ == "__main__":
    app = QApplication(sys.argv)
    mw = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(mw)
    mw.show()
    sys.exit(app.exec_())